/**
 * DTOs (Data Transfer Objects) and Command Models for 10x-Cards API
 *
 * This file contains all request and response type definitions used across the API.
 * All DTOs are derived from database entity types to ensure type safety and consistency.
 */

import type { Database } from "./db/database.types";

// =============================================================================
// Database Entity Base Types
// =============================================================================

/**
 * Flashcard entity as stored in the database
 */
export type FlashcardEntity = Database["public"]["Tables"]["flashcards"]["Row"];

/**
 * Generation entity as stored in the database
 */
export type GenerationEntity = Database["public"]["Tables"]["generations"]["Row"];

/**
 * Generation error log entity as stored in the database
 */
export type GenerationErrorLogEntity = Database["public"]["Tables"]["generation_error_logs"]["Row"];

// =============================================================================
// Enums and Literal Types
// =============================================================================

/**
 * Valid sources for flashcards
 * - ai-full: Generated by AI and accepted without editing
 * - ai-edited: Generated by AI but edited by user before accepting
 * - manual: Created manually by user
 */
export type FlashcardSource = "ai-full" | "ai-edited" | "manual";

/**
 * Valid sort fields for flashcard listing
 */
export type FlashcardSortField = "created_at" | "updated_at" | "front";

/**
 * Valid sort fields for generation listing
 */
export type GenerationSortField = "created_at" | "model";

/**
 * Sort order for listing operations
 */
export type SortOrder = "asc" | "desc";

// =============================================================================
// Common DTOs
// =============================================================================

/**
 * Pagination metadata for list responses
 */
export interface PaginationDTO {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
}

/**
 * Standard error response structure
 */
export interface ErrorResponseDTO {
  error: string;
  message: string;
  details?: unknown;
}

/**
 * Validation error detail for a single field
 */
export interface ValidationErrorDetailDTO {
  field: string;
  message: string;
}

/**
 * Validation error response with field-specific details
 */
export interface ValidationErrorResponseDTO extends ErrorResponseDTO {
  error: "Validation Error";
  details: ValidationErrorDetailDTO[];
}

// =============================================================================
// Flashcard DTOs
// =============================================================================

/**
 * Flashcard data transfer object
 * Used in API responses - excludes user_id for security
 * Derived from FlashcardEntity
 */
export type FlashcardDTO = Omit<FlashcardEntity, "user_id">;

/**
 * Request body for creating a single flashcard manually
 * Only requires front and back text
 * Source is auto-set to "manual", user_id is injected from JWT
 */
export interface CreateFlashcardDTO {
  front: string; // 1-200 characters
  back: string; // 1-500 characters
}

/**
 * Request body for updating an existing flashcard
 * Both fields are optional for partial updates
 */
export interface UpdateFlashcardDTO {
  front?: string; // 1-200 characters if provided
  back?: string; // 1-500 characters if provided
}

/**
 * Single flashcard item in a batch creation request
 * Used when accepting AI-generated flashcards
 */
export interface BatchFlashcardItemDTO {
  front: string; // 1-200 characters
  back: string; // 1-500 characters
  edited: boolean; // true if user edited AI proposal, false if accepted as-is
}

/**
 * Request body for creating multiple flashcards from AI generation
 * Used when user accepts some or all AI proposals
 */
export interface BatchCreateFlashcardsDTO {
  generation_id: number;
  flashcards: BatchFlashcardItemDTO[];
}

/**
 * Response for batch flashcard creation
 */
export interface BatchCreateFlashcardsResponseDTO {
  created_count: number;
  flashcards: FlashcardDTO[];
}

/**
 * Response for listing flashcards with pagination
 */
export interface FlashcardListResponseDTO {
  data: FlashcardDTO[];
  pagination: PaginationDTO;
}

/**
 * Response for successful flashcard deletion
 */
export interface DeleteFlashcardResponseDTO {
  message: string;
  id: number;
}

/**
 * Query parameters for listing flashcards
 */
export interface ListFlashcardsQueryDTO {
  page?: number; // default: 1
  limit?: number; // default: 20, max: 100
  sort?: FlashcardSortField; // default: "created_at"
  order?: SortOrder; // default: "desc"
  source?: FlashcardSource; // optional filter
  search?: string; // optional search in front/back
}

// =============================================================================
// Generation DTOs
// =============================================================================

/**
 * Generation data transfer object
 * Used in API responses - excludes sensitive fields (user_id, source_text_hash, updated_at)
 * Derived from GenerationEntity
 */
export type GenerationDTO = Omit<GenerationEntity, "user_id" | "source_text_hash" | "updated_at">;

/**
 * Flashcard proposal from AI generation
 * These are not yet saved to the database
 */
export interface FlashcardProposalDTO {
  front: string;
  back: string;
}

/**
 * Request body for creating a generation (generating flashcards from text)
 */
export interface CreateGenerationDTO {
  source_text: string; // 1000-10000 characters
}

/**
 * Response for creating a generation with AI proposals
 */
export interface CreateGenerationResponseDTO {
  generation: GenerationDTO;
  proposals: FlashcardProposalDTO[];
}

/**
 * Flashcard summary included in generation details
 * Lighter version of FlashcardDTO without some metadata
 */
export type FlashcardInGenerationDTO = Pick<FlashcardEntity, "id" | "front" | "back" | "source" | "created_at">;

/**
 * Generation with associated flashcards
 * Used when retrieving a single generation's details
 */
export interface GenerationWithFlashcardsDTO extends GenerationDTO {
  flashcards: FlashcardInGenerationDTO[];
}

/**
 * Statistics for user's generation history
 * Calculated on-demand when listing generations
 */
export interface GenerationStatisticsDTO {
  total_generations: number;
  total_flashcards_generated: number;
  total_flashcards_accepted: number;
  acceptance_rate: number; // 0.0 to 1.0
}

/**
 * Response for listing generations with pagination and statistics
 */
export interface GenerationListResponseDTO {
  data: GenerationDTO[];
  pagination: PaginationDTO;
  statistics: GenerationStatisticsDTO;
}

/**
 * Query parameters for listing generations
 */
export interface ListGenerationsQueryDTO {
  page?: number; // default: 1
  limit?: number; // default: 20, max: 100
  sort?: GenerationSortField; // default: "created_at"
  order?: SortOrder; // default: "desc"
  model?: string; // optional filter by model name
}

// =============================================================================
// Internal DTOs (for database operations)
// =============================================================================

/**
 * Data for inserting a new flashcard into the database
 * Used internally in API handlers
 */
export type FlashcardInsertDTO = Database["public"]["Tables"]["flashcards"]["Insert"];

/**
 * Data for updating a flashcard in the database
 * Used internally in API handlers
 */
export type FlashcardUpdateDTO = Database["public"]["Tables"]["flashcards"]["Update"];

/**
 * Data for inserting a new generation into the database
 * Used internally in API handlers
 */
export type GenerationInsertDTO = Database["public"]["Tables"]["generations"]["Insert"];

/**
 * Data for updating a generation in the database
 * Used internally in API handlers
 */
export type GenerationUpdateDTO = Database["public"]["Tables"]["generations"]["Update"];

/**
 * Data for inserting a generation error log into the database
 * Used internally when LLM API calls fail
 */
export type GenerationErrorLogInsertDTO = Database["public"]["Tables"]["generation_error_logs"]["Insert"];

// =============================================================================
// OpenRouter API Types
// =============================================================================

/**
 * Chat message in OpenRouter API format
 */
export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

/**
 * Response format configuration for structured JSON output
 */
export interface ResponseFormat {
  type: "json_schema";
  json_schema: {
    name: string;
    strict: boolean;
    schema: Record<string, unknown>;
  };
}

/**
 * Chat completion request parameters
 */
export interface ChatCompletionRequest {
  model: string;
  messages: ChatMessage[];
  temperature?: number;
  maxTokens?: number;
  responseFormat?: ResponseFormat;
  topP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  stop?: string | string[];
}

/**
 * Chat completion response from OpenRouter API
 */
export interface ChatCompletionResponse<T = unknown> {
  id: string;
  model: string;
  choices: {
    message: {
      role: string;
      content: string;
    };
    finish_reason: string;
    index: number;
  }[];
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
  parsed?: T;
}

/**
 * OpenRouter service configuration options
 */
export interface OpenRouterServiceOptions {
  baseUrl?: string;
  timeout?: number;
  httpReferer?: string;
  appTitle?: string;
  defaultModel?: string;
  retryAttempts?: number;
  retryDelay?: number;
}

/**
 * API call options for internal use
 */
export interface APICallOptions {
  temperature?: number;
  maxTokens?: number;
  responseFormat?: ResponseFormat;
  topP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
}

/**
 * OpenRouter error interface
 */
export interface OpenRouterError extends Error {
  code: string;
  statusCode?: number;
  details?: unknown;
  retryable: boolean;
}
